spring:
  datasource:
    password: prinRav!10
    url: jdbc:mysql://localhost:3306/DigitalBankdb
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
    show-sql: false

